keywords:
  - 'blockchain'
  - 'defi'
  - 'bitcoin'
  - 'btc'
  - 'crypto'
  - 'cryptocurrency'
  - 'nft'
  - 'ethereum'
  - 'binance'
  - 'altcoin'
  - 'namecoin'
  - 'solana'

min_faves: 100
min_retweets: 10
pages: 50
wait_time: 2